print("Ventajas de las Estufas Solares:")
print("1. Sostenibilidad: Reducción de la dependencia de combustibles fósiles.")
print("2. Energía Renovable: Fuente inagotable de energía.")
print("3. Bajas Emisiones: Emisiones de gases de efecto invernadero reducidas.")
print("4. Costos Operativos: Bajos costos operativos a largo plazo.")
print("5. Acceso a Energía Rural: Ideal para áreas remotas sin acceso a electricidad.")
print("6. Tecnología Simple: Diseños simples y fácil mantenimiento.")
print("7. Cocción Sostenible: Cocina sin consumir recursos no renovables.")
print("8. Descentralización: Menor necesidad de redes eléctricas centralizadas.")
print("9. Educación y Empoderamiento: Fomenta el conocimiento sobre energías renovables.")
print("10. Reducción de Pobreza: Contribuye a la autonomía energética en comunidades.")

print("\nDesventajas de las Estufas Solares:")
print("1. Dependencia de la Disponibilidad Solar: Eficiencia disminuye en climas nublados o lluviosos.")
print("2. Inversión Inicial Elevada: Requiere una inversión inicial que puede ser elevada.")
print("3. Emisiones en la Fabricación: Procesos de fabricación pueden generar emisiones.")
print("4. Variabilidad Climática: Variabilidad climática afecta la producción.")
print("5. Eficiencia en Climas Específicos: Limitado uso en climas con pocas horas de sol.")
print("6. Mantenimiento Necesario: Requiere cuidado en la limpieza de las superficies.")
print("7. No Adecuada para Alta Temperatura: No es adecuada para cocción de alta temperatura.")
print("8. Dependencia del Diseño: Eficiencia depende del diseño y ubicación geográfica.")
print("9. Limitado Uso en Climas Específicos: Eficiencia disminuye en climas con pocas horas de sol.")
print("10. Necesidad de Programas de Capacitación: Requiere programas de capacitación y apoyo.")
